extends Node

signal enemy_died(enemy: Node2D, position: Vector2, gp: int)
signal gp_collected(amount: int)
signal gp_changed(current: int, max_value: int)
signal evolution_ready()
signal evolution_chosen(evolution_id: String)
signal era_changed(era_name: String, era_index: int)
signal score_changed(new_score: int)
signal wave_changed(new_wave: int)
signal enemy_killed()
signal player_damaged(current_hp: int, max_hp: int)
signal player_died()
signal game_over()
signal hybrid_unlocked(hybrid_id: String)
signal boss_killed()
signal mini_boss_killed(mini_boss: Node2D, position: Vector2)
signal wave_announcement(wave: int, era_name: String)
signal mutation_ready()
signal mutation_applied(mutation_id: String)
signal wave_cleared(wave: int)
signal player_hit_enemy(enemy: Node2D, damage: int)
signal combo_changed(value: int)
signal combo_full(bar_index: int)
signal combo_broken()
signal part_unique_activated(effect: String, tier: int, behavior_id: String)
signal extinction_started(event_type: int)
signal extinction_ended()
signal era_transition_midpoint()
